package provider

import (
	"github.com/selefra/selefra-provider-aws/table_schema_generator"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/accessanalyzer"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/acm"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/apigateway"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/apigatewayv2"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/applicationautoscaling"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/apprunner"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/appsync"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/athena"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/autoscaling"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/backup"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/cloudformation"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/cloudfront"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/cloudhsmv2"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/cloudtrail"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/cloudwatch"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/cloudwatchlogs"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/codebuild"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/codepipeline"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/cognito"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/config"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/dax"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/directconnect"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/dms"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/docdb"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/dynamodb"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/ec2"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/ecr"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/ecrpublic"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/ecs"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/efs"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/eks"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/elasticache"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/elasticbeanstalk"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/elasticsearch"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/elbv1"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/elbv2"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/emr"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/eventbridge"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/firehose"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/fsx"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/glacier"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/glue"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/guardduty"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/iam"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/inspector"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/inspector2"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/iot"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/kinesis"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/kms"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/lambda"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/lightsail"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/mq"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/neptune"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/organizations"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/qldb"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/rds"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/redshift"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/resourcegroups"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/route53"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/s3"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/sagemaker"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/secretsmanager"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/ses"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/shield"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/sns"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/sqs"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/ssm"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/transfer"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/waf"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/wafregional"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/wafv2"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/workspaces"
	"github.com/selefra/selefra-provider-aws/table_schema_generator_tables/xray"
	"github.com/selefra/selefra-provider-sdk/provider/schema"
)

func GenTables() []*schema.Table {
	return []*schema.Table{
		table_schema_generator.GenTableSchema(&shield.TableAwsShieldProtectionGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&shield.TableAwsShieldProtectionsGenerator{}),
		table_schema_generator.GenTableSchema(&shield.TableAwsShieldSubscriptionsGenerator{}),
		table_schema_generator.GenTableSchema(&shield.TableAwsShieldAttacksGenerator{}),
		table_schema_generator.GenTableSchema(&waf.TableAwsWafWebAclsGenerator{}),
		table_schema_generator.GenTableSchema(&waf.TableAwsWafRuleGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&waf.TableAwsWafRulesGenerator{}),
		table_schema_generator.GenTableSchema(&waf.TableAwsWafSubscribedRuleGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&wafv2.TableAwsWafv2RegexPatternSetsGenerator{}),
		table_schema_generator.GenTableSchema(&wafv2.TableAwsWafv2RuleGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&wafv2.TableAwsWafv2ManagedRuleGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&wafv2.TableAwsWafv2WebAclsGenerator{}),
		table_schema_generator.GenTableSchema(&wafv2.TableAwsWafv2IpsetsGenerator{}),
		table_schema_generator.GenTableSchema(&autoscaling.TableAwsAutoscalingScheduledActionsGenerator{}),
		table_schema_generator.GenTableSchema(&autoscaling.TableAwsAutoscalingGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&autoscaling.TableAwsAutoscalingLaunchConfigurationsGenerator{}),
		table_schema_generator.GenTableSchema(&sagemaker.TableAwsSagemakerEndpointConfigurationsGenerator{}),
		table_schema_generator.GenTableSchema(&sagemaker.TableAwsSagemakerModelsGenerator{}),
		table_schema_generator.GenTableSchema(&sagemaker.TableAwsSagemakerNotebookInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&sagemaker.TableAwsSagemakerTrainingJobsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudwatch.TableAwsCloudwatchAlarmsGenerator{}),
		table_schema_generator.GenTableSchema(&kinesis.TableAwsKinesisStreamsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudfront.TableAwsCloudfrontDistributionsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudfront.TableAwsCloudfrontCachePoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&cloudtrail.TableAwsCloudtrailTrailsGenerator{}),
		table_schema_generator.GenTableSchema(&ecs.TableAwsEcsTaskDefinitionsGenerator{}),
		table_schema_generator.GenTableSchema(&ecs.TableAwsEcsClustersGenerator{}),
		table_schema_generator.GenTableSchema(&elasticsearch.TableAwsElasticsearchDomainsGenerator{}),
		table_schema_generator.GenTableSchema(&glacier.TableAwsGlacierDataRetrievalPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&glacier.TableAwsGlacierVaultsGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailInstanceSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailAlarmsGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailBucketsGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailLoadBalancersGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailDatabaseSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailDatabasesGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailContainerServicesGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailDisksGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailStaticIpsGenerator{}),
		table_schema_generator.GenTableSchema(&lightsail.TableAwsLightsailDistributionsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudhsmv2.TableAwsCloudhsmv2BackupsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudhsmv2.TableAwsCloudhsmv2ClustersGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2HostsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsRegionsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2FlowLogsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2TransitGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2InstanceStatusesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2ByoipCidrsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2VpnGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2RouteTablesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2KeyPairsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2EgressOnlyInternetGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2VpcsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2SecurityGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2EipsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2NatGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2CustomerGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2ReservedInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2InstancesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2VpcEndpointServicesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2InstanceTypesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2NetworkAclsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2EbsSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2NetworkInterfacesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2VpcEndpointServiceConfigurationsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2InternetGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2SubnetsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2VpcPeeringConnectionsGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2EbsVolumesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2ImagesGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2RegionalConfigGenerator{}),
		table_schema_generator.GenTableSchema(&ec2.TableAwsEc2VpcEndpointsGenerator{}),
		table_schema_generator.GenTableSchema(&cognito.TableAwsCognitoUserPoolsGenerator{}),
		table_schema_generator.GenTableSchema(&cognito.TableAwsCognitoIdentityPoolsGenerator{}),
		table_schema_generator.GenTableSchema(&qldb.TableAwsQldbLedgersGenerator{}),
		table_schema_generator.GenTableSchema(&codepipeline.TableAwsCodepipelineWebhooksGenerator{}),
		table_schema_generator.GenTableSchema(&codepipeline.TableAwsCodepipelinePipelinesGenerator{}),
		table_schema_generator.GenTableSchema(&efs.TableAwsEfsFilesystemsGenerator{}),
		table_schema_generator.GenTableSchema(&guardduty.TableAwsGuarddutyDetectorsGenerator{}),
		table_schema_generator.GenTableSchema(&lambda.TableAwsLambdaFunctionsGenerator{}),
		table_schema_generator.GenTableSchema(&lambda.TableAwsLambdaLayersGenerator{}),
		table_schema_generator.GenTableSchema(&lambda.TableAwsLambdaRuntimesGenerator{}),
		table_schema_generator.GenTableSchema(&sqs.TableAwsSqsQueuesGenerator{}),
		table_schema_generator.GenTableSchema(&apprunner.TableAwsApprunnerServicesGenerator{}),
		table_schema_generator.GenTableSchema(&appsync.TableAwsAppsyncGraphqlApisGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneSubnetGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneDbParameterGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneClusterSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneGlobalClustersGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneClusterParameterGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneClustersGenerator{}),
		table_schema_generator.GenTableSchema(&neptune.TableAwsNeptuneEventSubscriptionsGenerator{}),
		table_schema_generator.GenTableSchema(&route53.TableAwsRoute53DelegationSetsGenerator{}),
		table_schema_generator.GenTableSchema(&route53.TableAwsRoute53DomainsGenerator{}),
		table_schema_generator.GenTableSchema(&route53.TableAwsRoute53HealthChecksGenerator{}),
		table_schema_generator.GenTableSchema(&route53.TableAwsRoute53TrafficPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&route53.TableAwsRoute53HostedZonesGenerator{}),
		table_schema_generator.GenTableSchema(&xray.TableAwsXrayGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&xray.TableAwsXraySamplingRulesGenerator{}),
		table_schema_generator.GenTableSchema(&xray.TableAwsXrayEncryptionConfigGenerator{}),
		table_schema_generator.GenTableSchema(&elasticbeanstalk.TableAwsElasticbeanstalkApplicationsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticbeanstalk.TableAwsElasticbeanstalkEnvironmentsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticbeanstalk.TableAwsElasticbeanstalkApplicationVersionsGenerator{}),
		table_schema_generator.GenTableSchema(&emr.TableAwsEmrBlockPublicAccessConfigsGenerator{}),
		table_schema_generator.GenTableSchema(&emr.TableAwsEmrClustersGenerator{}),
		table_schema_generator.GenTableSchema(&mq.TableAwsMqBrokersGenerator{}),
		table_schema_generator.GenTableSchema(&cloudformation.TableAwsCloudformationStacksGenerator{}),
		table_schema_generator.GenTableSchema(&codebuild.TableAwsCodebuildProjectsGenerator{}),
		table_schema_generator.GenTableSchema(&elbv2.TableAwsElbv2TargetGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&elbv2.TableAwsElbv2LoadBalancersGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableAwsApigatewayDomainNamesGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableAwsApigatewayClientCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableAwsApigatewayUsagePlansGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableAwsApigatewayRestApisGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableAwsApigatewayVpcLinksGenerator{}),
		table_schema_generator.GenTableSchema(&apigateway.TableAwsApigatewayApiKeysGenerator{}),
		table_schema_generator.GenTableSchema(&apigatewayv2.TableAwsApigatewayv2ApisGenerator{}),
		table_schema_generator.GenTableSchema(&apigatewayv2.TableAwsApigatewayv2VpcLinksGenerator{}),
		table_schema_generator.GenTableSchema(&apigatewayv2.TableAwsApigatewayv2DomainNamesGenerator{}),
		table_schema_generator.GenTableSchema(&resourcegroups.TableAwsResourcegroupsResourceGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&secretsmanager.TableAwsSecretsmanagerSecretsGenerator{}),
		table_schema_generator.GenTableSchema(&dms.TableAwsDmsReplicationInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsSubnetGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsDbParameterGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsDbSecurityGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsClusterParameterGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsDbSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsEventSubscriptionsGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsClustersGenerator{}),
		table_schema_generator.GenTableSchema(&rds.TableAwsRdsClusterSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&ecr.TableAwsEcrRegistriesGenerator{}),
		table_schema_generator.GenTableSchema(&ecr.TableAwsEcrRegistryPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&ecr.TableAwsEcrRepositoriesGenerator{}),
		table_schema_generator.GenTableSchema(&eks.TableAwsEksClustersGenerator{}),
		table_schema_generator.GenTableSchema(&ses.TableAwsSesTemplatesGenerator{}),
		table_schema_generator.GenTableSchema(&sns.TableAwsSnsTopicsGenerator{}),
		table_schema_generator.GenTableSchema(&sns.TableAwsSnsSubscriptionsGenerator{}),
		table_schema_generator.GenTableSchema(&ssm.TableAwsSsmDocumentsGenerator{}),
		table_schema_generator.GenTableSchema(&ssm.TableAwsSsmInstancesGenerator{}),
		table_schema_generator.GenTableSchema(&ssm.TableAwsSsmParametersGenerator{}),
		table_schema_generator.GenTableSchema(&config.TableAwsConfigConfigurationRecordersGenerator{}),
		table_schema_generator.GenTableSchema(&config.TableAwsConfigConformancePacksGenerator{}),
		table_schema_generator.GenTableSchema(&dynamodb.TableAwsDynamodbTablesGenerator{}),
		table_schema_generator.GenTableSchema(&athena.TableAwsAthenaDataCatalogsGenerator{}),
		table_schema_generator.GenTableSchema(&athena.TableAwsAthenaWorkGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&backup.TableAwsBackupPlansGenerator{}),
		table_schema_generator.GenTableSchema(&backup.TableAwsBackupVaultsGenerator{}),
		table_schema_generator.GenTableSchema(&backup.TableAwsBackupRegionSettingsGenerator{}),
		table_schema_generator.GenTableSchema(&backup.TableAwsBackupGlobalSettingsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudwatchlogs.TableAwsCloudwatchlogsLogGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&cloudwatchlogs.TableAwsCloudwatchlogsMetricFiltersGenerator{}),
		table_schema_generator.GenTableSchema(&directconnect.TableAwsDirectconnectVirtualInterfacesGenerator{}),
		table_schema_generator.GenTableSchema(&directconnect.TableAwsDirectconnectConnectionsGenerator{}),
		table_schema_generator.GenTableSchema(&directconnect.TableAwsDirectconnectVirtualGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&directconnect.TableAwsDirectconnectGatewaysGenerator{}),
		table_schema_generator.GenTableSchema(&directconnect.TableAwsDirectconnectLagsGenerator{}),
		table_schema_generator.GenTableSchema(&elbv1.TableAwsElbv1LoadBalancersGenerator{}),
		table_schema_generator.GenTableSchema(&s3.TableAwsS3BucketsGenerator{}),
		table_schema_generator.GenTableSchema(&s3.TableAwsS3AccountsGenerator{}),
		table_schema_generator.GenTableSchema(&accessanalyzer.TableAwsAccessanalyzerAnalyzersGenerator{}),
		table_schema_generator.GenTableSchema(&applicationautoscaling.TableAwsApplicationautoscalingPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&workspaces.TableAwsWorkspacesWorkspacesGenerator{}),
		table_schema_generator.GenTableSchema(&workspaces.TableAwsWorkspacesDirectoriesGenerator{}),
		table_schema_generator.GenTableSchema(&dax.TableAwsDaxClustersGenerator{}),
		table_schema_generator.GenTableSchema(&docdb.TableAwsDocdbClustersGenerator{}),
		table_schema_generator.GenTableSchema(&inspector2.TableAwsInspector2FindingsGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotJobsGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotTopicRulesGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotBillingGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotThingTypesGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotStreamsGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotSecurityProfilesGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotThingGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotThingsGenerator{}),
		table_schema_generator.GenTableSchema(&iot.TableAwsIotCaCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&wafregional.TableAwsWafregionalRateBasedRulesGenerator{}),
		table_schema_generator.GenTableSchema(&wafregional.TableAwsWafregionalRuleGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&wafregional.TableAwsWafregionalWebAclsGenerator{}),
		table_schema_generator.GenTableSchema(&wafregional.TableAwsWafregionalRulesGenerator{}),
		table_schema_generator.GenTableSchema(&eventbridge.TableAwsEventbridgeEventBusesGenerator{}),
		table_schema_generator.GenTableSchema(&inspector.TableAwsInspectorFindingsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueSecurityConfigurationsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueTriggersGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueDevEndpointsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueDatacatalogEncryptionSettingsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueClassifiersGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueConnectionsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueJobsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueMlTransformsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueDatabasesGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueRegistriesGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueWorkflowsGenerator{}),
		table_schema_generator.GenTableSchema(&glue.TableAwsGlueCrawlersGenerator{}),
		table_schema_generator.GenTableSchema(&redshift.TableAwsRedshiftEventSubscriptionsGenerator{}),
		table_schema_generator.GenTableSchema(&redshift.TableAwsRedshiftSubnetGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&redshift.TableAwsRedshiftClustersGenerator{}),
		table_schema_generator.GenTableSchema(&transfer.TableAwsTransferServersGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheReplicationGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheParameterGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheSubnetGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheUsersGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheEngineVersionsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheGlobalReplicationGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheServiceUpdatesGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheReservedCacheNodesOfferingsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheClustersGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheUserGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheReservedCacheNodesGenerator{}),
		table_schema_generator.GenTableSchema(&elasticache.TableAwsElasticacheSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&fsx.TableAwsFsxSnapshotsGenerator{}),
		table_schema_generator.GenTableSchema(&fsx.TableAwsFsxVolumesGenerator{}),
		table_schema_generator.GenTableSchema(&fsx.TableAwsFsxDataRepositoryTasksGenerator{}),
		table_schema_generator.GenTableSchema(&fsx.TableAwsFsxBackupsGenerator{}),
		table_schema_generator.GenTableSchema(&fsx.TableAwsFsxFileSystemsGenerator{}),
		table_schema_generator.GenTableSchema(&fsx.TableAwsFsxStorageVirtualMachinesGenerator{}),
		table_schema_generator.GenTableSchema(&fsx.TableAwsFsxDataRepositoryAssociationsGenerator{}),
		table_schema_generator.GenTableSchema(&firehose.TableAwsFirehoseDeliveryStreamsGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamOpenidConnectIdentityProvidersGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamAccountsGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamSamlIdentityProvidersGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamRolesGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamVirtualMfaDevicesGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamGroupsGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamPasswordPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamServerCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamPoliciesGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamUsersGenerator{}),
		table_schema_generator.GenTableSchema(&iam.TableAwsIamCredentialReportsGenerator{}),
		table_schema_generator.GenTableSchema(&kms.TableAwsKmsAliasesGenerator{}),
		table_schema_generator.GenTableSchema(&kms.TableAwsKmsKeysGenerator{}),
		table_schema_generator.GenTableSchema(&organizations.TableAwsOrganizationsAccountsGenerator{}),
		table_schema_generator.GenTableSchema(&acm.TableAwsAcmCertificatesGenerator{}),
		table_schema_generator.GenTableSchema(&ecrpublic.TableAwsEcrpublicRepositoriesGenerator{}),
	}
}
